check_entry_key`: Split into sub-functions
Makes writing tests more straight forward and allows hiding checks conditionally
This makes carrying `$de_checks` unnecessary

diff --git a/xdg-terminal-exec b/xdg-terminal-exec
--- a/xdg-terminal-exec
+++ b/xdg-terminal-exec
@@ -296,112 +296,113 @@ alias find_entry_paths='IFS= find_entry_paths'
 check_entry_key() {
 	key="$1"
 	value="$2"
-	action="$3"
-	de_checks="$4"
+	entry_action="$3"
 
-	# Order of checks is important
 	case $key in
-	'Categories')
-		debug "checking for 'TerminalEmulator' in Categories '$value'"
-		IFS=';'
-		for category in $value; do
-			[ "$category" = "TerminalEmulator" ] && {
-				TERMINAL=true
-				return 0
-			}
-		done
-		# Default in this case is to fail
-		return 1
-		;;
-	'Actions')
-		# `It is not valid to have an action group for an action identifier not mentioned in the Actions key.
-		# Such an action group must be ignored by implementors.`
-		# ignore if no action requested
-		[ -z "$action" ] && return 0
-		debug "checking for '$action' in Actions '$value'"
-		IFS=';'
-		for check_action in $value; do
-			[ "$check_action" = "$action" ] && return 0
-		done
-		# Default in this case is to fail
-		return 1
-		;;
-	'OnlyShowIn')
-		case "$de_checks" in
-		true) debug "checking for intersecion between '${XDG_CURRENT_DESKTOP-}' and OnlyShowIn '$value'" ;;
-		false)
-			debug "skipping OnlyShowIn check"
-			return 0
-			;;
-		esac
-		IFS=';'
-		for target in $value; do
-			IFS=':'
-			for desktop in ${XDG_CURRENT_DESKTOP-}; do
-				[ "$desktop" = "$target" ] && return 0
-			done
-		done
-		# Default in this case is to fail
-		return 1
-		;;
-	'NotShowIn')
-		case "$de_checks" in
-		true) debug "checking for intersecion between '${XDG_CURRENT_DESKTOP-}' and NotShowIn '$value'" ;;
-		false)
-			debug "skipping NotShowIn check"
-			return 0
-			;;
-		esac
-		IFS=';'
-		for target in $value; do
-			IFS=':'
-			for desktop in ${XDG_CURRENT_DESKTOP-}; do
-				debug "checking NotShowIn match '$desktop'='$target'"
-				[ "$desktop" = "$target" ] && return 1
-			done
-		done
-		# Default in this case is to succeed
-		return 0
-		;;
-	'X-ExecArg' | 'ExecArg')
-		# Set global variable
-		EXECARG=$value
-		debug "read ExecArg '$EXECARG'"
-		;;
-	'TryExec')
-		debug "checking TryExec executable '$value'"
-		command -v "$value" > /dev/null || return 1
-		;;
-	'Hidden')
-		debug "checking boolean Hidden '$value'"
-		[ "$value" = 'true' ] && return 1
-		;;
-	'Exec')
-		# Only read key from requested group, marked by unset action ID
-		if [ -n "$entry_action" ]; then
-			debug "ignored Exec from wrong group"
-			return 0
-		fi
-		debug "read Exec '$value'"
-		# Set global variable
-		EXEC=$value
-		# Get first word from read Exec value
-		IFS="$OIFS"
-		eval "set -- $EXEC"
-		debug "checking Exec[0] executable '$1'"
-		command -v "$1" > /dev/null || return 1
-		;;
+	'X-ExecArg' | 'ExecArg') check_entry_execarg "$value" ;;
+	'Categories') check_entry_categories "$value" ;;
+	'OnlyShowIn') check_entry_onlyshowin "$value" ;;
+	'NotShowIn') check_entry_notshowin "$value" ;;
+	'Actions') check_entry_actions "$value" "$entry_action" ;;
+	'TryExec') check_entry_tryexec "$value" ;;
+	'Hidden') check_entry_hidden "$value" ;;
+	# Only read key from requested action group, marked by unset ID
+	'Exec') [ -z "$entry_action" ] && check_entry_exec "$value" ;;
 	esac
 	# By default unrecognised keys, empty lines and comments get ignored
 }
 # Mask IFS withing function to allow temporary changes
-alias check_entry='IFS= check_entry'
+alias check_entry_key='IFS= check_entry_key'
+
+# Bellow are all entry validating subfunctions, each responsible for a single key - value pair.
+# They're all in their own functions to make test writing more straight forward,
+# and to make hiding them conditionally possible. See `find_entry`.
+# Function `check_entry` is responsible for masking IFS etc. for them when called
+
+check_entry_categories() {
+	debug "checking for 'TerminalEmulator' in Categories '$1'"
+	IFS=';'
+	for category in $1; do
+		if [ "$category" = "TerminalEmulator" ]; then
+			TERMINAL=true
+			return 0
+		fi
+	done
+	# Default in this case is to fail
+	return 1
+}
+
+check_entry_onlyshowin() {
+	debug "checking for intersecion between '${XDG_CURRENT_DESKTOP-}' and OnlyShowIn '$1'"
+	IFS=';'
+	for target in $1; do
+		IFS=':'
+		for desktop in ${XDG_CURRENT_DESKTOP-}; do
+			[ "$desktop" = "$target" ] && return 0
+		done
+	done
+	# Default in this case is to fail
+	return 1
+}
+
+check_entry_notshowin() {
+	debug "checking for intersecion between '${XDG_CURRENT_DESKTOP-}' and NotShowIn '$1'"
+	IFS=';'
+	for target in $1; do
+		IFS=':'
+		for desktop in ${XDG_CURRENT_DESKTOP-}; do
+			debug "checking NotShowIn match '$desktop'='$target'"
+			[ "$desktop" = "$target" ] && return 1
+		done
+	done
+	# Default in this case is to succeed
+	return 0
+}
+
+check_entry_execarg() {
+	debug "read ExecArg '$1'"
+	# Set global variable
+	EXECARG=$1
+}
+
+check_entry_actions() {
+	# Ignore if no action ID was given
+	[ -z "$2" ] && return 0
+	debug "checking for '$2' in Actions '$1'"
+	# `[Action groups not mentioned in the Actions key] must be ignored by implementors.`
+	IFS=';'
+	for action in $1; do
+		[ "$action" = "$2" ] && return 0
+	done
+	# Default in this case is to fail
+	return 1
+}
+
+check_entry_tryexec() {
+	debug "checking TryExec executable '$1'"
+	command -v "$1" > /dev/null || return 1
+}
+
+check_entry_hidden() {
+	debug "checking boolean Hidden '$1'"
+	[ "$1" = 'true' ] && return 1
+}
+
+check_entry_exec() {
+	debug "read Exec '$1'"
+	# Set global variable
+	EXEC=$1
+	# Get first word from read Exec value
+	IFS="$OIFS"
+	eval "set -- $EXEC"
+	debug "checking Exec[0] executable '$1'"
+	command -v "$1" > /dev/null || return 1
+}
 
 # Read entry from given path
 read_entry_path() {
 	entry_path="$1"
 	entry_action="$2"
-	de_checks="$3"
 
 	debug "reading desktop entry '$entry_path' ${entry_action:+"action '$entry_action'"}"
 	# Let `read` trim leading/trailing spaces from the key and value
@@ -417,7 +418,7 @@ read_entry_path() {
 		# A `Key=Value` pair
 		[a-zA-Z0-9-]*)
 			# Check the pair and continue if valid
-			check_entry_key "$key" "$value" "${entry_action-}" "$de_checks" && continue
+			check_entry_key "$key" "$value" "${entry_action-}" && continue
 			# Reset values that might have been set
 			unset EXEC
 			unset EXECARG
@@ -432,12 +433,14 @@ read_entry_path() {
 
 # Loop through IDs and try to find a valid entry
 find_entry() {
-	# for explicitly listed entries do not apply DE *ShowIn limits
-	de_checks=false
+	# Do not enforce *ShowIn checks with explicitly listed entries
+	alias check_entry_onlyshowin=':'
+	alias check_entry_notshowin=':'
 	while IFS=':' read -r entry_id entry_action; do
-		# fallback entries ahead, enable *ShowIn checks
+		# Rest are fallback entries, enable *ShowIn checks
 		if [ "$entry_id" = '//fallback_start//' ]; then
-			de_checks=true
+			unalias check_entry_onlyshowin
+			unalias check_entry_notshowin
 			continue
 		fi
 		debug "matching path for entry ID '$entry_id'"
@@ -447,7 +450,7 @@ find_entry() {
 		eval "$entry_id"
 		# Unset the alias, so duplicate entries are skipped
 		unalias "$entry_id"
-		read_entry_path "$entry_path" "$entry_action" "$de_checks" || continue
+		read_entry_path "$entry_path" "$entry_action" || continue
 		# Check that the entry is a Terminal Emulator
 		[ -z "${TERMINAL-}" ] && continue
 		# Check that the entry is executable
